//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostImage
    {
        public int ID { get; set; }
        public int PostID { get; set; }
        public string ImagePath { get; set; }
        public DateTime AddDate { get; set; }
        public bool isDeleted { get; set; }
        public DateTime DeletedDate { get; set; } = DateTime.Now;
        public Nullable<int> LastUpdateUserID { get; set; }
        public DateTime LastUpdateDate { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual T_User T_User { get; set; }
    }
}
